<?php

namespace App\Admin\Controllers\District;

use App\Models\District\AreaStand;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Layout\Content;
use Encore\Admin\Show;

class AreaStandController extends AdminController
{
    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = '区站管理';

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        $grid = new Grid(new AreaStand());
        $grid->column('id', __('Id'));
        $grid->column('name', __('Name'));
        $grid->column('email', __('Email'));
        $grid->column('password', __('Password'));
        $grid->column('created_at', __('Created at'));
        $grid->column('updated_at', __('Updated at'));
        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(AreaStand::findOrFail($id));



        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        $form = new Form(new AreaStand());

        $form->distpicker([
            'province_id' => '省',
            'city_id'     => '市',
            'district_id' => '区'
        ]);
        $form->text('name');
        $form->number('operator');
        $form->number('explain');
        return $form;
    }


//    public function create(Content $content)
//    {
////        return parent::create($content); // TODO: Change the autogenerated stub
//        dd($content);
//    }
}
